 const db = {
            editions: [1], 
            hosts: { 1: "PL" }, 
            cities: { 1: "Gdańsk" }, 
            results: [], // Tutaj uzupełniaj wyniki
            countries: {
                "DZ": { name: "Algieria", code: "dz" }, "AO": { name: "Angola", code: "ao" }, "BJ": { name: "Benin", code: "bj" },
                "BW": { name: "Botswana", code: "bw" }, "BF": { name: "Burkina Faso", code: "bf" }, "BI": { name: "Burundi", code: "bi" },
                "TD": { name: "Czad", code: "td" }, "CD": { name: "Demokratyczna Republika Konga", code: "cd" }, "DJ": { name: "Dżibuti", code: "dj" },
                "EG": { name: "Egipt", code: "eg" }, "ER": { name: "Erytrea", code: "er" }, "SZ": { name: "Eswatini", code: "sz" },
                "ET": { name: "Etiopia", code: "et" }, "GA": { name: "Gabon", code: "ga" }, "GM": { name: "Gambia", code: "gm" },
                "GH": { name: "Ghana", code: "gh" }, "GN": { name: "Gwinea", code: "gn" }, "GW": { name: "Gwinea Bissau", code: "gw" },
                "GQ": { name: "Gwinea Równikowa", code: "gq" }, "CM": { name: "Kamerun", code: "cm" }, "KE": { name: "Kenia", code: "ke" },
                "KM": { name: "Komory", code: "km" }, "CG": { name: "Kongo", code: "cg" }, "LS": { name: "Lesotho", code: "ls" },
                "LR": { name: "Liberia", code: "lr" }, "LY": { name: "Libia", code: "ly" }, "MG": { name: "Madagaskar", code: "mg" },
                "MW": { name: "Malawi", code: "mw" }, "ML": { name: "Mali", code: "ml" }, "MA": { name: "Maroko", code: "ma" },
                "MR": { name: "Mauretania", code: "mr" }, "MU": { name: "Mauritius", code: "mu" }, "MZ": { name: "Mozambik", code: "mz" },
                "NA": { name: "Namibia", code: "na" }, "NE": { name: "Niger", code: "ne" }, "NG": { name: "Nigeria", code: "ng" },
                "ZA": { name: "Republika Południowej Afryki", code: "za" }, "CF": { name: "Republika Środkowoafrykańska", code: "cf" },
                "CV": { name: "Republika Zielonego Przylądka", code: "cv" }, "RW": { name: "Rwanda", code: "rw" }, "SN": { name: "Senegal", code: "sn" },
                "SC": { name: "Seszele", code: "sc" }, "SL": { name: "Sierra Leone", code: "sl" }, "SO": { name: "Somalia", code: "so" },
                "SD": { name: "Sudan", code: "sd" }, "SS": { name: "Sudan Południowy", code: "ss" }, "TZ": { name: "Tanzania", code: "tz" },
                "TG": { name: "Togo", code: "tg" }, "TN": { name: "Tunezja", code: "tn" }, "UG": { name: "Uganda", code: "ug" },
                "CI": { name: "Wybrzeże Kości Słoniowej", code: "ci" }, "ST": { name: "Wyspy Świętego Tomasza i Książęca", code: "st" },
                "ZM": { name: "Zambia", code: "zm" }, "ZW": { name: "Zimbabwe", code: "zw" },
                
                "AG": { name: "Antigua i Barbuda", code: "ag" }, "BS": { name: "Bahamy", code: "bs" }, "BB": { name: "Barbados", code: "bb" },
                "BZ": { name: "Belize", code: "bz" }, "DM": { name: "Dominika", code: "dm" }, "DO": { name: "Dominikana", code: "do" },
                "GD": { name: "Grenada", code: "gd" }, "GT": { name: "Gwatemala", code: "gt" }, "HT": { name: "Haiti", code: "ht" },
                "HN": { name: "Honduras", code: "hn" }, "JM": { name: "Jamajka", code: "jm" }, "CA": { name: "Kanada", code: "ca" },
                "CR": { name: "Kostaryka", code: "cr" }, "CU": { name: "Kuba", code: "cu" }, "MX": { name: "Meksyk", code: "mx" },
                "NI": { name: "Nikaragua", code: "ni" }, "PA": { name: "Panama", code: "pa" }, "KN": { name: "Saint Kitts i Nevis", code: "kn" },
                "LC": { name: "Saint Lucia", code: "lc" }, "VC": { name: "Saint Vincent i Grenadyny", code: "vc" }, "SV": { name: "Salwador", code: "sv" },
                "US": { name: "Stany Zjednoczone", code: "us" },
                
                "AR": { name: "Argentyna", code: "ar" }, "BO": { name: "Boliwia", code: "bo" }, "BR": { name: "Brazylia", code: "br" },
                "CL": { name: "Chile", code: "cl" }, "EC": { name: "Ekwador", code: "ec" }, "GY": { name: "Gujana", code: "gy" },
                "CO": { name: "Kolumbia", code: "co" }, "PY": { name: "Paragwaj", code: "py" }, "PE": { name: "Peru", code: "pe" },
                "SR": { name: "Surinam", code: "sr" }, "TT": { name: "Trynidad i Tobago", code: "tt" }, "UY": { name: "Urugwaj", code: "uy" },
                "VE": { name: "Wenezuela", code: "ve" },
                
                "AU": { name: "Australia", code: "au" }, "FJ": { name: "Fidżi", code: "fj" }, "KI": { name: "Kiribati", code: "ki" },
                "FM": { name: "Mikronezja", code: "fm" }, "NR": { name: "Nauru", code: "nr" }, "NZ": { name: "Nowa Zelandia", code: "nz" },
                "PW": { name: "Palau", code: "pw" }, "PG": { name: "Papua Nowa Gwinea", code: "pg" }, "WS": { name: "Samoa", code: "ws" },
                "TO": { name: "Tonga", code: "to" }, "TV": { name: "Tuvalu", code: "tv" }, "VU": { name: "Vanuatu", code: "vu" },
                "MH": { name: "Wyspy Marshalla", code: "mh" }, "SB": { name: "Wyspy Salomona", code: "sb" },
                
                "AF": { name: "Afganistan", code: "af" }, "SA": { name: "Arabia Saudyjska", code: "sa" }, "AM": { name: "Armenia", code: "am" },
                "AZ": { name: "Azerbejdżan", code: "az" }, "BH": { name: "Bahrajn", code: "bh" }, "BD": { name: "Bangladesz", code: "bd" },
                "BT": { name: "Bhutan", code: "bt" }, "BN": { name: "Brunei", code: "bn" }, "CN": { name: "Chiny", code: "cn" },
                "CY": { name: "Cypr", code: "cy" }, "PH": { name: "Filipiny", code: "ph" }, "GE": { name: "Gruzja", code: "ge" },
                "IN": { name: "Indie", code: "in" }, "ID": { name: "Indonezja", code: "id" }, "IQ": { name: "Irak", code: "iq" },
                "IR": { name: "Iran", code: "ir" }, "IL": { name: "Izrael", code: "il" }, "JP": { name: "Japonia", code: "jp" },
                "YE": { name: "Jemen", code: "ye" }, "JO": { name: "Jordania", code: "jo" }, "KH": { name: "Kambodża", code: "kh" },
                "QA": { name: "Katar", code: "qa" }, "KZ": { name: "Kazachstan", code: "kz" }, "KG": { name: "Kirgistan", code: "kg" },
                "KR": { name: "Korea Południowa", code: "kr" }, "KP": { name: "Korea Północna", code: "kp" }, "KW": { name: "Kuwejt", code: "kw" },
                "LA": { name: "Laos", code: "la" }, "LB": { name: "Liban", code: "lb" }, "MV": { name: "Malediwy", code: "mv" },
                "MY": { name: "Malezja", code: "my" }, "MM": { name: "Mjanma", code: "mm" }, "MN": { name: "Mongolia", code: "mn" },
                "NP": { name: "Nepal", code: "np" }, "OM": { name: "Oman", code: "om" }, "PK": { name: "Pakistan", code: "pk" },
                "PS": { name: "Palestyna", code: "ps" }, "RU": { name: "Rosja", code: "ru" }, "SG": { name: "Singapur", code: "sg" },
                "LK": { name: "Sri Lanka", code: "lk" }, "SY": { name: "Syria", code: "sy" }, "TJ": { name: "Tadżykistan", code: "tj" },
                "TH": { name: "Tajlandia", code: "th" }, "TL": { name: "Timor Wschodni", code: "tl" }, "TR": { name: "Turcja", code: "tr" },
                "TM": { name: "Turkmenistan", code: "tm" }, "UZ": { name: "Uzbekistan", code: "uz" }, "VN": { name: "Wietnam", code: "vn" },
                "AE": { name: "Zjednoczone Emiraty Arabskie", code: "ae" }, "TW": { name: "Tajwan", code: "tw" }, "HK": { name: "Hong Kong", code: "hk" },
                "MO": { name: "Makau", code: "mo" },
                
                "AL": { name: "Albania", code: "al" }, "AD": { name: "Andora", code: "ad" }, "AT": { name: "Austria", code: "at" },
                "BE": { name: "Belgia", code: "be" }, "BY": { name: "Białoruś", code: "by" }, "BA": { name: "Bośnia i Hercegowina", code: "ba" },
                "BG": { name: "Bułgaria", code: "bg" }, "HR": { name: "Chorwacja", code: "hr" }, "ME": { name: "Czarnogóra", code: "me" },
                "CZ": { name: "Czechy", code: "cz" }, "DK": { name: "Dania", code: "dk" }, "EE": { name: "Estonia", code: "ee" },
                "FI": { name: "Finlandia", code: "fi" }, "FR": { name: "Francja", code: "fr" }, "GR": { name: "Grecja", code: "gr" },
                "ES": { name: "Hiszpania", code: "es" }, "NL": { name: "Holandia", code: "nl" }, "IE": { name: "Irlandia", code: "ie" },
                "IS": { name: "Islandia", code: "is" }, "XK": { name: "Kosowo", code: "xk" }, "LI": { name: "Liechtenstein", code: "li" },
                "LT": { name: "Litwa", code: "lt" }, "LU": { name: "Luksemburg", code: "lu" }, "LV": { name: "Łotwa", code: "lv" },
                "MK": { name: "Macedonia Północna", code: "mk" }, "MT": { name: "Malta", code: "mt" }, "MD": { name: "Mołdawia", code: "md" },
                "MC": { name: "Monako", code: "mc" }, "DE": { name: "Niemcy", code: "de" }, "NO": { name: "Norwegia", code: "no" },
                "PL": { name: "Polska", code: "pl" }, "PT": { name: "Portugalia", code: "pt" }, "RO": { name: "Rumunia", code: "ro" }, 
                "SM": { name: "San Marino", code: "sm" }, "RS": { name: "Serbia", code: "rs" }, "SK": { name: "Słowacja", code: "sk" },
                "SI": { name: "Słowenia", code: "si" }, "CH": { name: "Szwajcaria", code: "ch" }, "SE": { name: "Szwecja", code: "se" }, 
                "UA": { name: "Ukraina", code: "ua" }, "HU": { name: "Węgry", code: "hu" }, "GB": { name: "Wielka Brytania", code: "gb" }, 
                "IT": { name: "Włochy", code: "it" }
            }
        };